### ISSUE TITLE
assert 1.4.0 buffer problem

### ISSUE THREAD

**Issue by joenoon** [defunctzombie/commonjs-assert#20]
Just noticed this from another project that was locked to assert@^1.3.0 (which pulled in 1.4.0 just now):

"Unable to resolve module buffer ..." - this is a react-native packager error, so not sure what other environments might be affected.  But it looks like assert now requires something that may not be available across various environments (node, browser, rn, etc): https://github.com/defunctzombie/commonjs-assert/compare/cc3c9...master

Or for some reason that buffer-shims dependency isn't enough.  I'm still looking into this and trying to figure out the best way forward.  My guess is I should lock my project to "1.3.0" for now.  Just wanted to open this issue in case others run into it.

**Comment by calvinmetcalf** [comment]
So it looks like you aren't using this in browserify or Webpack or
somewhere else that provides buffer

**Comment by joenoon** [comment]
Right, react-native has its own packager, so I guess it doesn't have buffer.  It sounds like we found a way forward in the other project, so feel free to close - it doesn't look like others are having issues.

**Comment by mk-pmb** [comment]
I think the time is ripe to have this closed by anyone who can do so.
