### ISSUE TITLE
deepEqual(true, [ 1 ])

### ISSUE THREAD

**Issue by mk-pmb** [defunctzombie/commonjs-assert#26]
Hi!
I'm developing an assert lib and it disagrees with this one:

```text
~/commonjs-assert$ git-log-concise -n 1
Mon 2016-06-27 02:58    f8975ca Add deepStrictEqual to the README (#23)

~/commonjs-assert$ nodejs -e 'require("./assert.js").deepEqual(true, [ 1 ]);'
[…]
AssertionError: true deepEqual [ 1 ]
```

I'd prefer my lib to also throw an error on this, but I can't find permission for that in the [CJS Unit Testing 1.0 spec](http://wiki.commonjs.org/wiki/Unit_Testing/1.0). According to my lib, rule 7.3 applies, because one of the values is not an object, so they don't "both pass" the typeof object test. As said, I prefer your module's behavior, so what reading of the spec did you come up with to legitimate throwing?

Node.js also throws, but [to me it seems](https://github.com/nodejs/node/issues/9063) it's unintentional there.

**Comment by calvinmetcalf** [comment]
this is the same as the node one so we did whatever they did

**Comment by mk-pmb** [comment]
I see, I probably didn't read the Readme proper enought the first time.

> The API is _derived from_ the commonjs 1.0

Well, derived is a weak term indeed, so do you even claim that this module conforms to the CJS spec?
If not, the module name and [line 45 of assert.js](https://github.com/defunctzombie/commonjs-assert/blob/master/assert.js#L45) would be quite confusing.

**Comment by calvinmetcalf** [comment]
This is literally the node code pulled out and slightly modified to work in
a browser

**Comment by mk-pmb** [comment]
Yeah, that part I understood, thus my question is now about mission and intent. Only when I understand the goals of this module, can I decide which of two possible features I'd like to request.
Do I understand correctly that

> modified to work in a browser

was the only intent for this package, and it is not `commonjs-assert`'s objective to be an assert module according to the CommonJS Unit Testing spec?

**Comment by ScottFreeCode** [comment]
For what it's worth, I'd rather like to see the relationship of this library to the Node internal module made more explicit in the readme and leave the matter of intention and spec compliance to the Node documentation (but, perhaps link that documentation here).

**Comment by mk-pmb** [comment]
Issue became irrelevant because we clarified that this assert doesn't aim to conform to the CommonJS spec.
