### ISSUE TITLE
Usefullness of this package ?

### ISSUE THREAD

**Issue by ncuillery** [defunctzombie/commonjs-assert#8]
Hi,

Is there a difference between this module and the built-in node assert module you mentioned in the README.md ?

I can't see the point of installing this module instead using the official one, but with nearly 500k downloads per month, I suppose I am wrong :wink: 

In which situation this module is needed ?

**Comment by coolaj86** [comment]
browser

**Comment by defunctzombie** [comment]
@ncuillery modules and choosing your own upgrade path.
